### ISSUE TITLE
Supporting signatures

### ISSUE THREAD

**Issue by fterpstra** [tudelft3d/cityjson#11]
would you consider supporting signatures of cityJSON files, for instance using the Jason Web Signature standard (https://www.rfc-editor.org/rfc/rfc7515.txt)? This would be a nice feature that enables a user to verify the authentic source of a city JSON document regardless of the way he acquired it.

**Comment by hugoledoux** [comment]
I read a bit, and I think it'd be a nice addition. I propose you make an example and describe how that would work? If you added a section in the file `docs/specs.rst` in the same style as the other ones and send me a PR I'd be very happy to accept it.

You could also had an example in the file `example-datasets/dummy-values/example.json`.

I'll take care of updating the schema.

**Comment by fterpstra** [comment]
Hi Hugo,
I did some more research on this and discussed my findings in the OGC security DWG. Basic conclusion is that rfc7515 is not very suitable. It is an enveloping signature format which means that if you use it your cityJSON payload will bepackeged as Base64encoded data inside a signature format. It is not an Enveloped signature format where the signature would just be an optional extra element in your format. I think the enveloping approach is not very user friendly for people who do not want to check the integrity of data. 
Unfortunately at the moment there are no suitable enveloped signature signature alternatives. https://cyberphone.github.io/doc/security/jcs.html does exist and is technically what i intended for digital signatures in JSON, but it is not a real standard and there is just one(or very few) implementation.
We are going to discuss this in the joint OGC/W3C spatial data on the web working group and see if maybe W3C sees a good solution for this.

**Comment by hugoledoux** [comment]
CityJSON is also under the w3c/ogc umbrella, so perfect!

Thanks for the update.
