### ISSUE TITLE
Allow remote references to texture image files

### ISSUE THREAD

**Issue by clausnagel** [tudelft3d/cityjson#13]
As for the current version of the specification, all texture image files are required to be in a local folder named `"appearances"` located next to the CityJSON file, and the `"image"` member of a texture object may only carry the name of the texture file.

Placing a large number of files in the same folder may cause troubles for some file systems. It would thus be good to allow organizing the texture files in subfolders below `"appearances"`, which requires storing relative paths in the `"image"` property.

However, local references to texture files are not sufficient if you want to serve CityJSON via a web service (well, at least if you do not want to create some sort of ZIP container at the server side). So it would even be better to allow both local and remote URI references to texture image files.

**Comment by hugoledoux** [comment]
Ok if WFS needs it then it must be done. 

Can you update the text (/docs/specs.rst) with an excerpt of the code and I'll take care of the schema?

**Comment by clausnagel** [comment]
Sorry, lost sight of this issue.

Well, since the "image" property is of type string, the schema itself already supports remote references. My proposal is to skip the requirement that all texture files have to be stored locally in a folder "appearances" next to the CityJSON file from the specification.

This would allow remote references:
```javascript
{
  "type": "JPG",
  "image": "http://some.domain.com/filename.jpg",
  ...
}
```
If you still want to store the texture file in an "appearances" folder next to the CityJSON file, all you have to do is:
```javascript
{
  "type": "JPG",
  "image": "appearances/filename.jpg",
  ...
}
``` 
But you would also be able to use multiple subfolders;
```javascript
{
  "type": "JPG",
  "image": "appearances/sub1/a.jpg",
  ...
},
{
  "type": "JPG",
  "image": "appearances/sub2/b.jpg",
  ...
}
``` 
And finally, also absolute local references would be supported:
```javascript
{
  "type": "JPG",
  "image": "c:\\some\folder\filename.jpg",
  ...
}
```
Small change, but big gain, in my oppinion.

**Comment by hugoledoux** [comment]
I agree, I changed the text (5b8c233d9f8b189cd50a17eeed0cedb5d6ec757a) and the schema as you said stays the same.
