### ISSUE TITLE
Allow vendor-specific properties for the root "CityJSON" object?

### ISSUE THREAD

**Issue by clausnagel** [tudelft3d/cityjson#14]
The current JSON schema disallows any properties on the root `CityJSON` object besides the predefined ones. 

Relaxing this limitation would allow adding vendor-specific properties that are neither covered by the predefined ones nor by the `metadata` element. Parsers can simply ignore these additional properties if they do not know how to deal with them.

**Comment by hugoledoux** [comment]
I agree, updated schema + validator + specs: 15a06dc47d13e5b0b1af5de07e097d74654ae7ea
