### ISSUE TITLE
Add bbox property to city objects

### ISSUE THREAD

**Issue by clausnagel** [tudelft3d/cityjson#15]
Would be nice to have an optional `"bbox"` property on all city objects like `Building,` `Bridge,` etc. 

One use case I have in mind is light-weight responses to queries. For some applications, I need to retrieve city objects from a CityGML datastore according to some spatial or thematic filters. But I am only interested in the number, type and thematic properties of the matching city objects, not in their possibly heavy-weight geometry. 

CityJSON allows skipping the geometry, which helps in reducing the file size and thus in having fast responses to queries. However, when skipping the geometry there is no further spatial information about the city objects. With a `"bbox"` property you still would have light-weight spatial information per city object (which you could use, for example, to fly to the object on a web map).

**Comment by hugoledoux** [comment]
good case: added in 72b7f626a5ea7557a236d20f1c0a65fdcacb9b4f
