### ISSUE TITLE
texture files must be local?

### ISSUE THREAD

**Issue by balazsdukai** [tudelft3d/cityjson#22]
The specification at [Appearance Object](http://www.cityjson.org/en/0.6/specs/#appearance-object) states that *"texture files have to be local and put in folder named "appearances" located in the same folder as the CityJSON file (thus requests to web services as is the case with CityGML are not supported)."*

Then it states that a [Textrue Object](http://www.cityjson.org/en/0.6/specs/#texture-object) *"must have one member with the name "image", whose value is a string with the name of the file. This file can be a URL (eg "http://www.hugo.com/filename.jpg"), a relative path (eg "appearances/myroof.jpg"), or an absolute path (eg "/home/elvis/mycityjson/appearances/myroof.jpg")."*

Which one is true?

**Comment by hugoledoux** [comment]
latter.

I changed my mind and obviously didn't update all the text. Cheers for pointing out.
