### ISSUE TITLE
update to metadata

### ISSUE THREAD

**Issue by hugoledoux** [tudelft3d/cityjson#25]
There's a couple of things for the three of us to discuss next week but for initial changes:
-there seems to be a slight misunderstanding and I thought we had changed it after you commented on it for the paper but it shouldn't be semanticClasses but thematicModels, because otherwise I get confused about them not being windows and doors, etc
-metadataPointOfContact is not ISO it's the metadata creator so in this case the same as the contact for the dataset
-metadata date stamp is also the creation date of the metadata
-metadata standard name is ISO 19115 - Geographic Information -Metadata
-metadata standard version is ISO 19115:2014(E)

--> specs.rst, example-metadata.json, metadata.json (schema) all need to be updated

**Comment by Athelena** [comment]
Updated all and committed
