### ISSUE TITLE
Are new semantic surfaces listed in "extensions" member?

### ISSUE THREAD

**Issue by clausnagel** [tudelft3d/cityjson#30]
The CityJSON extension mechanism allows adding new semantic surfaces by simply adding "+" to their name. My question is whether these names also have to be listed in the `"extensions"` member of the `"CityJSON"` object? The current specification only says that new City Objects are to be listed there.

**Comment by hugoledoux** [comment]
Right now no, it's just something starting with a "+". The main reason is I am not sure how it could be done with JSON schema without redefining all the Geometry Objects... I don't see any solutions to this, except defining them in a separate list somehow, and specific code parsing this. But with https://json-schema.org/ validation it seems impossible (or I am missing something).

I just noticed actually that the schema v0.8 have an error, the "+" thing is not properly implemented, I'll fix ASAP.

**Comment by hugoledoux** [comment]
the bug has been fixed: 18f80b02d22ec2c04ea0675d3b2b4a9cd76069c5 

it'll be in v0.9, it's in the 'development' branch
