### ISSUE TITLE
type and version easier to identify that a file is a CityJSON file

### ISSUE THREAD

**Issue by hugoledoux** [tudelft3d/cityjson#4]
```js
{
  "type": "CityModel",
  "version": "http://www.cityjson.org/version/0.2",
}
```
-->
```js
{
  "type": "CityJSON",
  "version": "0.2",
  "schema": "http://www.cityjson.org/en/0.2/_downloads/cityjson-v02.schema.json"
}
```

**Comment by kenohori** [comment]
This fixes a big problem with CityGML, which is that a program can't know if a file is a CityGML file easily.
* Fetching schemas in URLs -> needs internet access, takes time and links are often broken (or down)
* Comparing namespace strings with known URLs -> schema can be hosted somewhere else
* Assuming that CityModel means CityGML -> non-CityGML files can use that name too

**Comment by clausnagel** [comment]
@kenohori The CityGML namespaces are fix and independent from a server location. So in fact it's quite simple to understand if a XML dataset contains CityGML elements.

**Comment by kenohori** [comment]
@clausnagel You are right. I was assuming that the namespace URIs were pointing to actual locations...

That being said, I still feel like this is a chance to correct a part of CityGML that doesn't make much sense. I've been trying to go to the addresses of various CityGML namespaces and many of them just point to 404 errors.

**Comment by clausnagel** [comment]
> Namespace URIs are purely formal identifiers. They are not the addresses of a page, and they are not meant to be followed as links ([O'Reilly XML in a nutshell](https://docstore.mik.ua/orelly/xml/xmlnut/ch04_02.htm))

With that said, I agree that there nevertheless could be some content at the CityGML namespace URIs, such as the corresponding XML schema document. I can bring that into the CityGML group at OGC.

**Comment by hugoledoux** [comment]
done 032d46c0bb7d51f2848a0c04401e5fe6c49ef2af
