### ISSUE TITLE
Wrong name and type of storeysHeightsAboveGround and storeysHeightsBelowGround

### ISSUE THREAD

**Issue by clausnagel** [tudelft3d/cityjson#7]
The attributes `"storeysHeightsAboveGround"` and `"storeysHeightsBelowGround"` of `Building` and `BuildingPart` defined in the [v0.2 Json schema](http://www.cityjson.org/en/0.2/_downloads/cityjson-v02.schema.json) have a wrong name compared to the their [CityGML](http://schemas.opengis.net/citygml/building/2.0/building.xsd) counterparts. It should be `"storeyHeights..."` - so no plural for storey.

Moreover, also their type differs. In CityGML, both attributes are of type `gml:MeasureOrNullListType`, whereas they are defined to be of type integer in CityJSON. An array of double would be more appropriate.

**Comment by hugoledoux** [comment]
oh right, indeed. Thanks for pointing this out.

Fixed for v0.3: 
989444f8d20371784af7ceb911184a5fcb49d747
