### ISSUE TITLE
is no Semantic Surface Object, should it be ``{}`` or ``null``

### ISSUE THREAD

**Issue by hugoledoux** [tudelft3d/cityjson#8]
```js
"semantics": [
      {
        "type": "RoofSurface",
        "slope": 16.4,
        "solar-potential": 5
      },
      {},
      {
        "type": "GroundSurface"
      }
    ]
```

or ``null`` instead? Or both?

**Comment by clausnagel** [comment]
Only `null` in my opinion.

**Comment by kenohori** [comment]
I agree, `null` seems best.

**Comment by hugoledoux** [comment]
thanks all, I was looking at this and thought null should be there, you
confirmed this.

But it seems that we our new proposal that won’t be necessary actually!

**Comment by hugoledoux** [comment]
no necessary anymore, from v0.5 the Semantic Surface are enumerated and links to them provided.
